### ISSUE TITLE
Feature: drag item and scroll

### ISSUE THREAD

**Issue by JayShoe** [dflex-js/dflex#280]
I would like to be able to drag item number 1 to below item number 1000 by dragging down. I would like to drag item number 1000 to above item number 1 by dragging the item up. Right now It does not have the option to scroll. 

Bonus, make the speed variable based on distance of the drag from bottom of screen.   The further the faster.

**Comment by jalal246** [comment]
@JayShoe If things go according to the plan this feature should be introduced next release.
