### ISSUE TITLE
Drag and scrolling doesn't work

### ISSUE THREAD

**Issue by X-Ryl669** [dflex-js/dflex#577]
In the large list demo, drag the item 2 and move to the bottom of the list.
Then, while still dragging, scroll the container. The dragged item is not following the scroll, and it's becoming crazy.

**Comment by jalal246** [comment]
Hi @X-Ryl669, The demo version (2.x.x) is behind the current version (3.7.0). In both versions, the scroll is supported. However, prior to v3, the scroll was restricted outside the container. Reason: transformation has to calculate visible elements and then animate the scrolling which is something introduced recently in v3.
